/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nexes_manager_dorca3_function */

#ifndef _Included_com_neowine_manager_dorca3_function
#define _Included_com_neowine_manager_dorca3_function
#ifdef __cplusplus
extern "C" {
#endif
#undef com_neowine_manager_dorca3_function_DORCA3_USB_PID
#define com_neowine_manager_dorca3_function_DORCA3_USB_PID 4666L
#undef com_neowine_manager_dorca3_function_DORCA3_USB_VID
#define com_neowine_manager_dorca3_function_DORCA3_USB_VID 1046L
/*
 * Class:     com_nexes_manager_dorca3_function
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_neowine_manager_dorca3_1function_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_nexes_manager_dorca3_function
 * Method:    AES_CIPHER
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_com_neowine_manager_dorca3_1function_AES_1CIPHER
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
