/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nexes_manager_JniBrige */

#ifndef _Included_com_neowine_manager_JniBrige
#define _Included_com_neowine_manager_JniBrige
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nexes_manager_JniBrige
 * Method:    OPENSSLENC
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_neowine_manager_JniBrige_OPENSSLENC
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     com_nexes_manager_JniBrige
 * Method:    OPENSSLDEC
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_neowine_manager_JniBrige_OPENSSLDEC
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     com_nexes_manager_JniBrige
 * Method:    AES_CIPHER
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_com_neowine_manager_JniBrige_AES_1CIPHER
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
